### ISSUE TITLE
Having trouble building

### ISSUE THREAD

**Issue by dilllxd** [m1k1o/neko-vpn#1]
Hi! Currently my plan is to run a couple neko rooms and run one of them through neko-vpn, however I'm having trouble building the container. These are my current configs with some stuff redacted/changed for privacy/security, not really sure where I'm messing up. If you need anything else let me know. I also am not using traefik :)

**Build Error**

![image](https://github.com/m1k1o/neko-vpn/assets/36942187/b23418f4-bf3a-4ec5-9ff3-eed7464f4b6d)

**Docker Compose for nekovpn**
```
nekovpn:
    build: "/mnt/storage/nekovpn/ovpn-nodejs"
    restart: "unless-stopped"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - net_admin
    dns:
     - 8.8.8.8
     - 8.8.4.4
    volumes:
      - "/dev/net:/dev/net:z"
      - "/mnt/storage/nekovpn/vpn:/vpn"
    command: "80 miami.ovpn"
```

and this is my file structure

**/mnt/storage/nekovpn**

![image](https://github.com/m1k1o/neko-vpn/assets/36942187/d7647132-0c51-4a7d-a0a5-77e3c2555a16)

**/mnt/storage/nekovpn/vpn**

![image](https://github.com/m1k1o/neko-vpn/assets/36942187/2d86f103-2c63-4591-a617-bcf6156c9be2)

**/mnt/storage/nekovpn/.env**

```
#
# vpn config
#
DEFAULT_VPN="miami.ovpn"

# View more at:
# https://github.com/m1k1o/ovpn-nodejs/tree/f62621f5440b717b3e3ae344ab2476f5571e1f87#group-regex
FILE_REGEXP=""

# View more at:
# https://github.com/m1k1o/ovpn-nodejs/tree/f62621f5440b717b3e3ae344ab2476f5571e1f87#group-regex
GROUP_REGEXP=""

#
# neko config
#
ADMIN_PASSWORD="admin"
USER_PASSWORD="neko"
DOWNLOAD_DIR="./downloads"
PORT_RANGE="57000-57010"
DEFAULT_SCREEN="1360x768@60"

#
# only if using docker-compose.yml
#
HTTP_PORT="80"

#
# only if using docker-compose.traefik.yml
#
TRAEFIK_NETWORK_NAME="traefik_default"
TRAEFIK_RULE="Host(`neko.example.com`)"
TRAEFIK_ENTRYPOINTS="web-secure"
TRAEFIK_CERTRESOLVER="letsencrypt"
```

**/mnt/storage/nekovpn/vpn/miami.ovpn**

```
client
dev tun
proto udp
remote <redacted> 54783

nobind
auth-user-pass .auth

resolv-retry infinite

auth SHA512
cipher AES-256-CBC
verb 2
mute-replay-warnings
remote-cert-tls server
persist-key
persist-tun

key-direction 1
<ca>
-----BEGIN CERTIFICATE-----
<redacted>
-----END CERTIFICATE-----
</ca>
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
<redacted>
-----END OpenVPN Static key V1-----
</tls-auth>
```

**/mnt/storage/nekovpn/vpn/.auth**
```
example-username
example-password
```
